apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

# Scale up for prod
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
    target:
      kind: Deployment
      name: practice-app-deployment

# Override configmap values for prod
configMapGenerator:
  - name: practice-app-config
    behavior: merge
    literals:
      - APP_ENV=production
