apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: practice-app-dev
  namespace: argocd

  # This finalizer ensures that when the Application is deleted, Argo CD will clean up any resources it created in the cluster.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rimrachai-marma/argocd-practice-app
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true # Delete resources removed from Git
      selfHeal: true # Re-sync if someone manually changes cluster state
    syncOptions:
      - CreateNamespace=true
