apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
type: Opaque
stringData:
  # GitHub Personal Access Token with repo write access
  # Create one at: GitHub → Settings → Developer settings → Personal access tokens
  # Required scopes: repo (full)
  username: rimrachai-marma
  password: # < GitHub PAT> --- IGNORE ---


  # This is the repo Image Updater will commit back to
  # It commits a file like: .argocd-source-practice-app-dev.yaml
  # into your overlay directory with the new image tag
