apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app-deployment
  labels:
    app: practice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
        - name: practice-app
          image: rimra/argocd-practice-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: practice-app-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
