apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: rimra/argocd-practice-app
    newTag: latest # placeholder — Image Updater will override this
